// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Diagrama_Clase;


public class Carte {

    private int idCarte;
    private String nume;
    private String autor;
    private String editura;
    private boolean status;

    public Carte(String nume, String autor, String editura) {
        this.nume = nume;
        this.autor = autor;
        this.editura = editura;
        this.status = true;
    }

    public Carte(Carte c) {
        this.nume = c.nume;
        this.autor = c.autor;
        this.editura = c.editura;
        this.status = true;
    }

    // Setters
    public void setIdCarte(int idCarte) {
        this.idCarte = idCarte;
    }

    public void setNume(String nume) {
        this.nume = nume;
    }

    public void setAutor(String autor) {
        this.autor = autor;
    }

    public void setEditura(String editura) {
        this.editura = editura;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    // Getters
    public int getIdCarte() {
        return idCarte;
    }

    public String getNume() {
        return nume;
    }

    public String getAutor() {
        return autor;
    }

    public String getEditura() {
        return editura;
    }

    public boolean isStatus() {
        return status;
    }

    public void afisare() {
        System.out.println("Cartea " + idCarte);
        System.out.println("Titlu: " + nume);
        System.out.println("Autor: " + autor);
        System.out.println("Editrura: " + editura + "\n");
    }

};
