// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Diagrama_Clase;


public class Permis {

    private boolean permisValid;
    private int nrCartiNereturnate;

    public Permis(){
        permisValid = true;
        nrCartiNereturnate = 0;
    }

    // Setters
    public void setPermisValid(boolean permisValid) {
        this.permisValid = permisValid;
    }

    public void setNrCartiNereturnate(int nrCartiNereturnate) {
        this.nrCartiNereturnate = nrCartiNereturnate;
    }

    // Getters
    public boolean isPermisValid() {
        return permisValid;
    }

    public int getNrCartiNereturnate() {
        return nrCartiNereturnate;
    }

    public void afisare() {
        System.out.println("Date permis:");
        if (permisValid) {
            System.out.println("Penalizari: nu");
        } else {
            System.out.println("Penalizari: da");
        }
        System.out.println("Nr. carti nereturnate:" + nrCartiNereturnate + "\n");
    }

};
